# Generated by Django 4.2.8 on 2023-12-08 18:23

from django.db import migrations, models
import imagekit.models.fields
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_category_options_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=webapp.models.user_directory_path, verbose_name='Изображение блюда'),
        ),
    ]
