# Generated by Django 4.2.8 on 2023-12-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория рецептов', 'verbose_name_plural': 'Категории рецептов'},
        ),
    ]
